version: '3.1'

services:

  web :
    image : ocsinventory/ocsinventory-docker-image:latest
    container_name : ocsinventory-server
    environment :
      OCS_DBNAME : ocsweb
      OCS_DBSERVER_READ : ocsinventory-db
      OCS_DBSERVER_WRITE : ocsinventory-db
      OCS_DBUSER : ocs
      OCS_DBPASS : ocspw
    volumes :
      - ocssrv:/usr/share/ocsinventory-reports/
      - ocssrv:/etc/ocsinventory-reports/
      - ocssrv:/var/lib/ocsinventory-reports/
    links :
      - db
    ports :
      - 80:80
      - 443:443

  db :
    image : mariadb
    container_name : ocsinventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : S3cur1ty!
      MYSQL_USER : ocs
      MYSQL_PASSWORD : ocspw
      MYSQL_DATABASE : ocsweb
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - sqldata:/var/lib/mysql
    ports :
      - 3306:3306

volumes:
  sqldata:
    driver: local
  ocssrv:
    driver: local